### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "6580442304",
  "amount": 14000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 14000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "aa45c96f61a647df9dbda46c00de9ce1",
  "accountNumber": "1000000000",
  "amount": 14000
}

### query transaction
GET http://localhost:8080/transaction/55253cbbb55246c5a5a6eab03f3846c7
Accept: application/json

