### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "8303523539",
  "amount": 1400
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "8303523539",
  "amount": 14000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "4f3a72ed04274a03bf4be2675a8b2a00",
  "accountNumber": "8303523539",
  "amount": 1400
}

### query transaction
GET http://localhost:8080/transaction/55253cbbb55246c5a5a6eab03f3846c7
Accept: application/json

