### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "7092758348",
  "amount": 1400
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "7092758348",
  "amount": 14000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "eec841c318b549eba619f98f4b8db863",
  "accountNumber": "7092758348",
  "amount": 1400
}

### query transaction
GET http://localhost:8080/transaction/b491ec1286b64d26b572f9a758887ed7
Accept: application/json

